# Site settings
title: I don't byte
email: oliver@jaun.org
description: > # this means to ignore newlines until "baseurl:"
  Blog about Java Programming and Software Architecture
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idontbyte.jaun.org" # the base hostname & protocol for your site
#github_username:  olijaun
author: Oliver Jaun
author_about: /about
permalink: /blog/:year/:month/:title
# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  #- jekyll-sitemap
  - jekyll-plantuml
paginate: 5
paginate_path: "/page:num/"
excerpt_separator: <!--more-->

sass:
    style: :compressed
