# Site settings
title: Oliver Jaun
email: oliver@jaun.org
description: > # this means to ignore newlines until "baseurl:"
  Oliver Jaun's personal Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oliver.jaun.org" # the base hostname & protocol for your site
#github_username:  olijaun

# Build settings
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
paginate: 5
paginate_path: "/page:num/"
excerpt_separator: <!--more-->

sass:
    style: :compressed
